### ISSUE TITLE
HAL eats full CPU on one core to paint some QT elements

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#71] opened 2019-05-13 11:17 UTC
After some time, HAL starts to consume 100% CPU on one core. Attaching a debugger yielded this call stack at the moment of stopping the offending thread.

```
libhal_gui.so!gui_graph_gate::paint(gui_graph_gate * const this, QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) (/home/rene/git/hal/src/gui/graph_layouter/gui_graph_gate.cpp:212)
libQt5Widgets.so.5![Unknown/Just-In-Time compiled code] (Unbekannte Quelle:0)
libQt5Widgets.so.5!QGraphicsView::paintEvent(QPaintEvent*) (Unbekannte Quelle:0)
libhal_gui.so!graph_layouter_view::paintEvent(graph_layouter_view * const this, QPaintEvent * event) (/home/rene/git/hal/src/gui/graph_layouter/graph_layouter_view.cpp:292)
libQt5Widgets.so.5!QWidget::event(QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QFrame::event(QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QGraphicsView::viewportEvent(QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplicationPrivate::notify_helper(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplication::notify(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplication::notifyInternal2(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::sendPaintEvent(QRegion const&) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) (Unbekannte Quelle:0)
libQt5Widgets.so.5![Unknown/Just-In-Time compiled code] (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidgetPrivate::syncBackingStore() (Unbekannte Quelle:0)
libQt5Widgets.so.5!QWidget::event(QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplicationPrivate::notify_helper(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplication::notify(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplication::notifyInternal2(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (Unbekannte Quelle:0)
libQt5Widgets.so.5![Unknown/Just-In-Time compiled code] (Unbekannte Quelle:0)
libQt5Core.so.5!QObject::event(QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QGraphicsScene::event(QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplicationPrivate::notify_helper(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplication::notify(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplication::notifyInternal2(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (Unbekannte Quelle:0)
libQt5Core.so.5![Unknown/Just-In-Time compiled code] (Unbekannte Quelle:0)
libglib-2.0.so.0!g_main_context_dispatch (Unbekannte Quelle:0)
libglib-2.0.so.0![Unknown/Just-In-Time compiled code] (Unbekannte Quelle:0)
libglib-2.0.so.0!g_main_context_iteration (Unbekannte Quelle:0)
libQt5Core.so.5!QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (Unbekannte Quelle:0)
libQt5Core.so.5!QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplication::exec() (Unbekannte Quelle:0)
libhal_gui.so!plugin_gui::exec(plugin_gui * const this, program_arguments & args) (/home/rene/git/hal/src/gui/plugin_gui.cpp:129)
redirect_control_to_interactive_ui(const std::__cxx11::string & name, program_arguments & args) (/home/rene/git/hal/src/main.cpp:78)
main(int argc, const char ** argv) (/home/rene/git/hal/src/main.cpp:124)
```

**Comment by swallat** [comment] 2019-05-14 08:34
@RenWal Could you elaborate a bit more on when this issue occurs?

**Comment by RenWal** [comment] 2019-05-14 19:35
So far this looks rather random to me (which is not really helpful). I'll report back if I can pinpoint an exact action that triggers this.

**Comment by Slowpoke42** [comment] 2019-05-14 21:08
@RenWal Don't bother. If the problem is related to the current graph view it's likely not worth your time, because I'm currently rewriting that feature from scratch. The graph view classes used in the master branch (layouters, items, scene, view and widget) are essentially obsolete and serve more of a placeholder function. In the unlikely event that this problem is still present in the new version we can reopen this issue.

**Comment by swallat** [comment] 2019-05-15 04:46
I'm closing this issue for now.

**Closed by swallat** 2019-05-15 04:46 UTC
Labels: bug, discussion, gui
